### ISSUE TITLE
Error: Cannot find path: [object Object] in UpdateChunk.js

### ISSUE THREAD

**Issue by Leko** [Leko/hothouse#27]
```
Error: Cannot find path: [object Object]
    at UpdateChunk.getUpdatesBy (/usr/local/lib/node_modules/hothouse/dist/UpdateChunk.js:25:13)
    at main (/usr/local/lib/node_modules/hothouse/dist/cli.js:63:66)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by Leko** [comment]
It's careless miss https://github.com/Leko/hothouse/blob/f48b704e8b45cd4f75df94a18f6f516231474c60/packages/hothouse/src/cli.js#L67
