### ISSUE TITLE
TypeError: (0 , _parseGithubRepoUrl.default) is not a function

### ISSUE THREAD

**Issue by Leko** [Leko/hothouse#29]
```
TypeError: (0 , _parseGithubRepoUrl.default) is not a function
    at GitHub.shaToTag (/usr/local/lib/node_modules/hothouse/dist/Hosting/GitHub.js:22:59)
    at Engine.getTag (/usr/local/lib/node_modules/hothouse/dist/Engine.js:189:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by Leko** [comment]
Hm... It's not encounted in console debug...

```
  async shaToTag(token, repositoryUrl, sha) {
    console.log({_parseGithubRepoUrl})
    console.log(_parseGithubRepoUrl.default)
    console.log({repositoryUrl})
    console.log(_parseGithubRepoUrl.default(repositoryUrl))
    console.log((0, _parseGithubRepoUrl.default))
    console.log((0, _parseGithubRepoUrl.default)(repositoryUrl))
    const [owner, repo] = (0, _parseGithubRepoUrl.default)(repositoryUrl); // /repos/yargs/yargs/git/tags/57a39cb8fe5051b9d9bb87fb789cc0d6d2363ce6
```
