### ISSUE TITLE
Does not work with recent versions of yarn.

### ISSUE THREAD

**Issue by remotezygote** [Leko/hothouse#79]
Recent versions (since 1.3.2 at least) of yarn output their `--json` line-by-line, so the parsing code in this package does not work at all, specifically this line: https://github.com/Leko/hothouse/blob/master/packages/%40hothouse/client-yarn/src/index.js#L42

Not only is the output incompatible, it looks like even if you go grab the right line of output, it still doesn't work, since the format has changed.

Yarn issue for reference and rationale: https://github.com/yarnpkg/yarn/issues/714

**Comment by remotezygote** [comment]
This does not seem to be working properly. I am getting the following error:

**Comment by remotezygote** [comment]
Debug output: (redactions mine)

```
DEBUG=hothouse* hothouse -t <redacted>
  hothouse:cli CLI options are: { _: [],
  help: false,
  version: false,
  'per-package': true,
  p: true,
  perPackage: true,
  bail: true,
  b: true,
  'dry-run': false,
  dryRun: false,
  t: 'b910ad82787487662cbe2091b25935e5afce14ac',
  token: 'b910ad82787487662cbe2091b25935e5afce14ac',
  concurrency: 8,
  ignore: [],
  '$0': 'hothouse',
  'package-manager': undefined,
  'repository-structure': undefined } +0ms
  hothouse:Engine dryRun=false +0ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Yarn: matched=true +13ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +1ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Yarn: matched=true +21ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Detect package manager in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +1ms
  hothouse:PackageManagerResolver Yarn: matched=true +23ms
  hothouse:PackageManagerResolver Yarn: matched=true +24ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:PackageManagerResolver Yarn: matched=true +20ms
  hothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +1ms
  hothouse:PackageManagerResolver Yarn: matched=true +23ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +1ms
  hothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +1ms
  hothouse:PackageManagerResolver Yarn: matched=true +27ms
  hothouse:PackageManagerResolver Yarn: matched=true +19ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +1ms
  hothouse:PackageManagerResolver Yarn: matched=true +23ms
mhothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +5ms
  hothouse:RepositoryStructureResolver Detect repository structure in: /Users/<redacted>/workspaces/<redacted> +0ms
  hothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +31ms
  hothouse:RepositoryStructureResolver YarnWorkspaces: matched=true +1ms
  hothouse:Engine Found 25 packages: [ <redacted but correct list of packages /> ] +1s
undefined
Please report issue from here: https://github.com/Leko/hothouse/issues
TypeError: Cannot read property 'babel-eslint' of undefined
    at table.data.body.map.update (/Users/<redacted>/.config/yarn/global/node_modules/@hothouse/client-yarn/dist/index.js:69:34)
    at Array.map (<anonymous>)
    at updates.reduce (/Users/<redacted>/.config/yarn/global/node_modules/@hothouse/client-yarn/dist/index.js:63:39)
    at Array.reduce (<anonymous>)
    at Yarn.getUpdates (/Users/<redacted>/.config/yarn/global/node_modules/@hothouse/client-yarn/dist/index.js:62:30)
    at _default (/Users/<redacted>/.config/yarn/global/node_modules/hothouse/dist/tasks/fetchUpdates.js:22:40)
    at module.exports (/Users/<redacted>/.config/yarn/global/node_modules/hothouse/dist/worker.js:28:40)
    at process.<anonymous> (/Users/<redacted>/.config/yarn/global/node_modules/threads/lib/worker.node/slave.js:84:20)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
Please report issue from here: https://github.com/Leko/hothouse/issues
```

**Comment by remotezygote** [comment]
I opened https://github.com/Leko/hothouse/pull/83 that fixes _this_ issue. This uncovered #84 though, which I think I also have a fix for (just accounting for workspaces now).

**Comment by remotezygote** [comment]
Thanks for your help! I'm excited to see this work!
