### ISSUE TITLE
`SyntaxError: Unexpected token` is occered at local(mac)

### ISSUE THREAD

**Issue by yamatatsu** [Leko/hothouse#82]
I hothoused in my local. and got SyntaxError.

```
> hothouse -t ${my-token}
SyntaxError: Unexpected token { in JSON at position 222
    at JSON.parse (<anonymous>)
    at Yarn.getUpdates (/Users/yamamototatsuya/.config/yarn/global/node_modules/@hothouse/client-yarn/dist/index.js:52:27)
    at Engine.getUpdates (/Users/yamamototatsuya/.config/yarn/global/node_modules/hothouse/dist/Engine.js:65:47)
    at main (/Users/yamamototatsuya/.config/yarn/global/node_modules/hothouse/dist/cli.js:49:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```

I try `yarn outdated` in node repl.

```js
> _result.stdout
'{"type":"info","data":"Color legend : \\n \\"<red>\\"    : Major Update backward-incompatible updates \\n \\"<yellow>\\" : Minor Update backward-compatible features \\n \\"<green>\\"  : Patch Update backward-compatible bug fixes"}\n{"type":"table","data":{"head":["Package","Current","Wanted","Latest","Package Type","URL"],"body":[["babel-eslint","8.2.5","8.2.6","8.2.6","devDependencies","https://github.com/babel/babel-eslint"],["flow-bin","0.75.0","0.75.0","0.76.0","devDependencies","https://github.com/flowtype/flow-bin#readme"],["jest","23.3.0","23.4.0","23.4.0","devDependencies","https://jestjs.io/"]]}}\n'

> JSON.parse(_result.stdout)
SyntaxError: Unexpected token { in JSON at position 222
```

**Comment by Leko** [comment]
@yamatatsu Thank you for your reporting.
What version of hothouse are you using?

Currently (`Fri Jul 13 2018 00:22:33 GMT+0900 (JST)`) we published new version to support line json of Yarn outdated.
Please try hothouse@0.4.0.

**Comment by Leko** [comment]
I'll close this issue.
If you have any trouble in the latest version, please re-open this issue.
